name: .NET Core Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore --configuration ${{ matrix.configuration }}

    - name: Build projects
      run: dotnet build Testowanie/Testowanie.csproj Testowanie.Tests/Testowanie.Tests.csproj --configuration ${{ matrix.configuration }} --no-restore

    - name: Execute unit tests
      run: dotnet test Testowanie.Tests/Testowanie.Tests.csproj --configuration ${{ matrix.configuration }} --no-build --verbosity normal

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: ./Testowanie/bin/${{ matrix.configuration }}
