name: .NET Core Build, Test and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

env:
  DOTNET_VERSION: '8.0.x'
  CONFIGURATION: 'Release'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Używamy obu systemów operacyjnych
        configuration: [Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies for Testowanie
      run: dotnet restore Testowanie/Testowanie.csproj

    - name: Restore dependencies for Testowanie.Tests
      run: dotnet restore Testowanie.Tests/Testowanie.Tests.csproj

    - name: Build Testowanie project
      run: dotnet build Testowanie/Testowanie.csproj --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Build Testowanie.Tests project
      run: dotnet build Testowanie.Tests/Testowanie.Tests.csproj --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Execute unit tests
      run: dotnet test Testowanie.Tests/Testowanie.Tests.csproj --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: ./Testowanie/bin/${{ env.CONFIGURATION }}

  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.1-${{ github.sha }}
        release_name: Release v0.1-${{ github.sha }}
        draft: false
        prerelease: false

    - name: Prepare release assets (Linux)
      run: |
        mkdir -p release
        cp -r ./Testowanie/bin/${{ env.CONFIGURATION }}/* release/
        zip -r release/Testowanie-${{ env.CONFIGURATION }}.zip release/

    - name: Upload Release Assets (Linux)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/Testowanie-${{ env.CONFIGURATION }}.zip
        asset_name: Testowanie-${{ env.CONFIGURATION }}.zip
        asset_content_type: application/zip

    - name: Prepare release assets (Windows)
      run: |
        mkdir -p release
        cp -r ./Testowanie/bin/${{ env.CONFIGURATION }}/* release/
        zip -r release/Testowanie-${{ env.CONFIGURATION }}.zip release/

    - name: Upload Release Assets (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/Testowanie-${{ env.CONFIGURATION }}.zip
        asset_name: Testowanie-${{ env.CONFIGURATION }}.zip
        asset_content_type: application/zip
