name: Build, test, and release .csproj

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

permissions:
  contents: write
  packages: write

env:
  DOTNET_VERSION: '8.0.x'
  CONFIGURATION: 'Release'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: |
        dotnet restore Testowanie/Testowanie.csproj
        dotnet restore Testowanie.Tests/Testowanie.Tests.csproj

    - name: Build projects
      run: |
        dotnet build Testowanie/Testowanie.csproj --configuration ${{ env.CONFIGURATION }} --no-restore
        dotnet build Testowanie.Tests/Testowanie.Tests.csproj --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Execute unit tests
      run: dotnet test Testowanie.Tests/Testowanie.Tests.csproj --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BuildArtifacts-${{ matrix.os }}
        path: ./Testowanie/bin/${{ env.CONFIGURATION }}

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download build artifacts (Linux)
      uses: actions/download-artifact@v3
      with:
        name: BuildArtifacts-ubuntu-latest
        path: release-linux
    
    - name: Download build artifacts (Windows)
      uses: actions/download-artifact@v3
      with:
        name: BuildArtifacts-windows-latest
        path: release-windows

    - name: Calculate tag and release version
      id: calculate
      run: |
        TAG_NAME="v0.1-$((28 - $GITHUB_RUN_NUMBER))"
        echo "RELEASE_VER=${RELEASE_VER}" >> $GITHUB_ENV
    
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VER }}
        release_name: ${{ env.RELEASE_VER }}
        draft: false
        prerelease: false

    - name: Package release assets
      run: |
        zip -rj testowanie-bin-windows.zip release-windows/net8.0/*
        zip -rj testowanie-bin-linux.zip release-linux/net8.0/*
    
    - name: Display directory structure
      run: |
        ls -al

    - name: Upload ZIP Archive (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: testowanie-bin-windows.zip
        asset_name: testowanie-bin-windows.zip
        asset_content_type: application/zip
    
    - name: Upload ZIP Archive (Linux)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: testowanie-bin-linux.zip
        asset_name: testowanie-bin-linux.zip
        asset_content_type: application/zip
